site_name:  data structure
site_url: https://dengking.github.io/data-structure
site_description: Project documentation with Markdown.
site_author: DengKing


repo_url: https://github.com/dengking/data-structure

edit_uri: ""



theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
        
nav:
- Home: wikipedia-Data-structure.md
- structure: structure.md
- ADT:
  - wikipedia-Abstract-data-type: ADT/wikipedia-Abstract-data-type.md
- data-structure:
  - tree:
    - application-of-tree: data-structure/tree/application-of-tree.md
    - tree-and-recursion: data-structure/tree/tree-and-recursion.md
    - tree-and-stack: data-structure/tree/tree-and-stack.md

    
extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: ïƒ
    - admonition
    - def_list
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs
        
plugins:
    - search